/**
 * API v1
 * DocSpring is a service that helps you fill out and sign PDF templates.
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

export class CreateSubmissionDataRequestData {
    'authPhoneNumberHash'?: string | null;
    'authProvider'?: string | null;
    'authSecondFactorType'?: CreateSubmissionDataRequestData.AuthSecondFactorTypeEnum;
    'authSessionIdHash'?: string | null;
    'authSessionStartedAt'?: string | null;
    'authType': CreateSubmissionDataRequestData.AuthTypeEnum;
    'authUserIdHash'?: string | null;
    'authUsernameHash'?: string | null;
    'email': string | null;
    'fields'?: Array<string> | null;
    'metadata'?: object;
    'name'?: string | null;
    'order'?: number;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "authPhoneNumberHash",
            "baseName": "auth_phone_number_hash",
            "type": "string"
        },
        {
            "name": "authProvider",
            "baseName": "auth_provider",
            "type": "string"
        },
        {
            "name": "authSecondFactorType",
            "baseName": "auth_second_factor_type",
            "type": "CreateSubmissionDataRequestData.AuthSecondFactorTypeEnum"
        },
        {
            "name": "authSessionIdHash",
            "baseName": "auth_session_id_hash",
            "type": "string"
        },
        {
            "name": "authSessionStartedAt",
            "baseName": "auth_session_started_at",
            "type": "string"
        },
        {
            "name": "authType",
            "baseName": "auth_type",
            "type": "CreateSubmissionDataRequestData.AuthTypeEnum"
        },
        {
            "name": "authUserIdHash",
            "baseName": "auth_user_id_hash",
            "type": "string"
        },
        {
            "name": "authUsernameHash",
            "baseName": "auth_username_hash",
            "type": "string"
        },
        {
            "name": "email",
            "baseName": "email",
            "type": "string"
        },
        {
            "name": "fields",
            "baseName": "fields",
            "type": "Array<string>"
        },
        {
            "name": "metadata",
            "baseName": "metadata",
            "type": "object"
        },
        {
            "name": "name",
            "baseName": "name",
            "type": "string"
        },
        {
            "name": "order",
            "baseName": "order",
            "type": "number"
        }    ];

    static getAttributeTypeMap() {
        return CreateSubmissionDataRequestData.attributeTypeMap;
    }
}

export namespace CreateSubmissionDataRequestData {
    export enum AuthSecondFactorTypeEnum {
        None = <any> 'none',
        PhoneNumber = <any> 'phone_number',
        Totp = <any> 'totp',
        MobilePush = <any> 'mobile_push',
        SecurityKey = <any> 'security_key',
        Fingerprint = <any> 'fingerprint'
    }
    export enum AuthTypeEnum {
        None = <any> 'none',
        Password = <any> 'password',
        Oauth = <any> 'oauth',
        EmailLink = <any> 'email_link',
        PhoneNumber = <any> 'phone_number',
        Ldap = <any> 'ldap',
        Saml = <any> 'saml'
    }
}
