/* tslint:disable */
/* eslint-disable */
/**
 * API v1
 * DocSpring is a service that helps you fill out and sign PDF templates.
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface AddFieldsData
 */
export interface AddFieldsData {
    /**
     * 
     * @type {Array<object>}
     * @memberof AddFieldsData
     */
    fields: Array<object>;
}

/**
 * Check if a given object implements the AddFieldsData interface.
 */
export function instanceOfAddFieldsData(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "fields" in value;

    return isInstance;
}

export function AddFieldsDataFromJSON(json: any): AddFieldsData {
    return AddFieldsDataFromJSONTyped(json, false);
}

export function AddFieldsDataFromJSONTyped(json: any, ignoreDiscriminator: boolean): AddFieldsData {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'fields': json['fields'],
    };
}

export function AddFieldsDataToJSON(value?: AddFieldsData | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'fields': value.fields,
    };
}

