/* tslint:disable */
/* eslint-disable */
/**
 * API v1
 * DocSpring is a service that helps you fill out and sign PDF templates.
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface AddFieldsTemplateResponse
 */
export interface AddFieldsTemplateResponse {
    /**
     * 
     * @type {string}
     * @memberof AddFieldsTemplateResponse
     */
    status: AddFieldsTemplateResponseStatusEnum;
    /**
     * 
     * @type {Array<string>}
     * @memberof AddFieldsTemplateResponse
     */
    errors?: Array<string>;
    /**
     * 
     * @type {Array<number>}
     * @memberof AddFieldsTemplateResponse
     */
    newFieldIds?: Array<number>;
}


/**
 * @export
 */
export const AddFieldsTemplateResponseStatusEnum = {
    Success: 'success',
    Error: 'error'
} as const;
export type AddFieldsTemplateResponseStatusEnum = typeof AddFieldsTemplateResponseStatusEnum[keyof typeof AddFieldsTemplateResponseStatusEnum];


/**
 * Check if a given object implements the AddFieldsTemplateResponse interface.
 */
export function instanceOfAddFieldsTemplateResponse(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "status" in value;

    return isInstance;
}

export function AddFieldsTemplateResponseFromJSON(json: any): AddFieldsTemplateResponse {
    return AddFieldsTemplateResponseFromJSONTyped(json, false);
}

export function AddFieldsTemplateResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): AddFieldsTemplateResponse {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'status': json['status'],
        'errors': !exists(json, 'errors') ? undefined : json['errors'],
        'newFieldIds': !exists(json, 'new_field_ids') ? undefined : json['new_field_ids'],
    };
}

export function AddFieldsTemplateResponseToJSON(value?: AddFieldsTemplateResponse | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'status': value.status,
        'errors': value.errors,
        'new_field_ids': value.newFieldIds,
    };
}

