/* tslint:disable */
/* eslint-disable */
/**
 * API v1
 * DocSpring is a service that helps you fill out and sign PDF templates.
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface AuthenticationError
 */
export interface AuthenticationError {
    /**
     * 
     * @type {string}
     * @memberof AuthenticationError
     */
    status?: AuthenticationErrorStatusEnum;
    /**
     * 
     * @type {string}
     * @memberof AuthenticationError
     */
    error: string;
}


/**
 * @export
 */
export const AuthenticationErrorStatusEnum = {
    Error: 'error'
} as const;
export type AuthenticationErrorStatusEnum = typeof AuthenticationErrorStatusEnum[keyof typeof AuthenticationErrorStatusEnum];


/**
 * Check if a given object implements the AuthenticationError interface.
 */
export function instanceOfAuthenticationError(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "error" in value;

    return isInstance;
}

export function AuthenticationErrorFromJSON(json: any): AuthenticationError {
    return AuthenticationErrorFromJSONTyped(json, false);
}

export function AuthenticationErrorFromJSONTyped(json: any, ignoreDiscriminator: boolean): AuthenticationError {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'status': !exists(json, 'status') ? undefined : json['status'],
        'error': json['error'],
    };
}

export function AuthenticationErrorToJSON(value?: AuthenticationError | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'status': value.status,
        'error': value.error,
    };
}

