/* tslint:disable */
/* eslint-disable */
/**
 * API v1
 * DocSpring is a service that helps you fill out and sign PDF templates.
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CombinedSubmissionData
 */
export interface CombinedSubmissionData {
    /**
     * 
     * @type {number}
     * @memberof CombinedSubmissionData
     */
    expiresIn?: number;
    /**
     * 
     * @type {object}
     * @memberof CombinedSubmissionData
     */
    metadata?: object;
    /**
     * 
     * @type {string}
     * @memberof CombinedSubmissionData
     */
    password?: string;
    /**
     * 
     * @type {Array<string>}
     * @memberof CombinedSubmissionData
     */
    submissionIds: Array<string>;
    /**
     * 
     * @type {boolean}
     * @memberof CombinedSubmissionData
     */
    test?: boolean;
}

/**
 * Check if a given object implements the CombinedSubmissionData interface.
 */
export function instanceOfCombinedSubmissionData(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "submissionIds" in value;

    return isInstance;
}

export function CombinedSubmissionDataFromJSON(json: any): CombinedSubmissionData {
    return CombinedSubmissionDataFromJSONTyped(json, false);
}

export function CombinedSubmissionDataFromJSONTyped(json: any, ignoreDiscriminator: boolean): CombinedSubmissionData {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'expiresIn': !exists(json, 'expires_in') ? undefined : json['expires_in'],
        'metadata': !exists(json, 'metadata') ? undefined : json['metadata'],
        'password': !exists(json, 'password') ? undefined : json['password'],
        'submissionIds': json['submission_ids'],
        'test': !exists(json, 'test') ? undefined : json['test'],
    };
}

export function CombinedSubmissionDataToJSON(value?: CombinedSubmissionData | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'expires_in': value.expiresIn,
        'metadata': value.metadata,
        'password': value.password,
        'submission_ids': value.submissionIds,
        'test': value.test,
    };
}

