/* tslint:disable */
/* eslint-disable */
/**
 * API v1
 * DocSpring is a service that helps you fill out and sign PDF templates.
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CreateFolderAttributes
 */
export interface CreateFolderAttributes {
    /**
     * 
     * @type {string}
     * @memberof CreateFolderAttributes
     */
    name: string;
    /**
     * 
     * @type {string}
     * @memberof CreateFolderAttributes
     */
    parentFolderId?: string;
}

/**
 * Check if a given object implements the CreateFolderAttributes interface.
 */
export function instanceOfCreateFolderAttributes(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "name" in value;

    return isInstance;
}

export function CreateFolderAttributesFromJSON(json: any): CreateFolderAttributes {
    return CreateFolderAttributesFromJSONTyped(json, false);
}

export function CreateFolderAttributesFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateFolderAttributes {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'name': json['name'],
        'parentFolderId': !exists(json, 'parent_folder_id') ? undefined : json['parent_folder_id'],
    };
}

export function CreateFolderAttributesToJSON(value?: CreateFolderAttributes | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'name': value.name,
        'parent_folder_id': value.parentFolderId,
    };
}

