/* tslint:disable */
/* eslint-disable */
/**
 * API v1
 * DocSpring is a service that helps you fill out and sign PDF templates.
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { UploadTemplateData } from './UploadTemplateData';
import {
    UploadTemplateDataFromJSON,
    UploadTemplateDataFromJSONTyped,
    UploadTemplateDataToJSON,
} from './UploadTemplateData';

/**
 * 
 * @export
 * @interface CreateTemplateFromUploadData
 */
export interface CreateTemplateFromUploadData {
    /**
     * 
     * @type {UploadTemplateData}
     * @memberof CreateTemplateFromUploadData
     */
    template: UploadTemplateData;
}

/**
 * Check if a given object implements the CreateTemplateFromUploadData interface.
 */
export function instanceOfCreateTemplateFromUploadData(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "template" in value;

    return isInstance;
}

export function CreateTemplateFromUploadDataFromJSON(json: any): CreateTemplateFromUploadData {
    return CreateTemplateFromUploadDataFromJSONTyped(json, false);
}

export function CreateTemplateFromUploadDataFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateTemplateFromUploadData {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'template': UploadTemplateDataFromJSON(json['template']),
    };
}

export function CreateTemplateFromUploadDataToJSON(value?: CreateTemplateFromUploadData | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'template': UploadTemplateDataToJSON(value.template),
    };
}

