/* tslint:disable */
/* eslint-disable */
/**
 * API v1
 * DocSpring is a service that helps you fill out and sign PDF templates.
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { CreateFolderAttributes } from './CreateFolderAttributes';
import {
    CreateFolderAttributesFromJSON,
    CreateFolderAttributesFromJSONTyped,
    CreateFolderAttributesToJSON,
} from './CreateFolderAttributes';

/**
 * 
 * @export
 * @interface CreateFolderData
 */
export interface CreateFolderData {
    /**
     * 
     * @type {CreateFolderAttributes}
     * @memberof CreateFolderData
     */
    folder: CreateFolderAttributes;
}

/**
 * Check if a given object implements the CreateFolderData interface.
 */
export function instanceOfCreateFolderData(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "folder" in value;

    return isInstance;
}

export function CreateFolderDataFromJSON(json: any): CreateFolderData {
    return CreateFolderDataFromJSONTyped(json, false);
}

export function CreateFolderDataFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateFolderData {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'folder': CreateFolderAttributesFromJSON(json['folder']),
    };
}

export function CreateFolderDataToJSON(value?: CreateFolderData | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'folder': CreateFolderAttributesToJSON(value.folder),
    };
}

