/* tslint:disable */
/* eslint-disable */
/**
 * API v1
 * DocSpring is a service that helps you fill out and sign PDF templates.
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CreateCustomFileResponse
 */
export interface CreateCustomFileResponse {
    /**
     * 
     * @type {string}
     * @memberof CreateCustomFileResponse
     */
    status: CreateCustomFileResponseStatusEnum;
    /**
     * 
     * @type {Array<string>}
     * @memberof CreateCustomFileResponse
     */
    errors?: Array<string>;
    /**
     * 
     * @type {object}
     * @memberof CreateCustomFileResponse
     */
    customFile: object;
}


/**
 * @export
 */
export const CreateCustomFileResponseStatusEnum = {
    Success: 'success',
    Error: 'error'
} as const;
export type CreateCustomFileResponseStatusEnum = typeof CreateCustomFileResponseStatusEnum[keyof typeof CreateCustomFileResponseStatusEnum];


/**
 * Check if a given object implements the CreateCustomFileResponse interface.
 */
export function instanceOfCreateCustomFileResponse(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "status" in value;
    isInstance = isInstance && "customFile" in value;

    return isInstance;
}

export function CreateCustomFileResponseFromJSON(json: any): CreateCustomFileResponse {
    return CreateCustomFileResponseFromJSONTyped(json, false);
}

export function CreateCustomFileResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateCustomFileResponse {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'status': json['status'],
        'errors': !exists(json, 'errors') ? undefined : json['errors'],
        'customFile': json['custom_file'],
    };
}

export function CreateCustomFileResponseToJSON(value?: CreateCustomFileResponse | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'status': value.status,
        'errors': value.errors,
        'custom_file': value.customFile,
    };
}

