/* tslint:disable */
/* eslint-disable */
/**
 * API v1
 * DocSpring is a service that helps you fill out and sign PDF templates.
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { Submission } from './Submission';
import {
    SubmissionFromJSON,
    SubmissionFromJSONTyped,
    SubmissionToJSON,
} from './Submission';

/**
 * 
 * @export
 * @interface CreateSubmissionResponse
 */
export interface CreateSubmissionResponse {
    /**
     * 
     * @type {string}
     * @memberof CreateSubmissionResponse
     */
    status: CreateSubmissionResponseStatusEnum;
    /**
     * 
     * @type {Array<string>}
     * @memberof CreateSubmissionResponse
     */
    errors?: Array<string>;
    /**
     * 
     * @type {Submission}
     * @memberof CreateSubmissionResponse
     */
    submission: Submission;
}


/**
 * @export
 */
export const CreateSubmissionResponseStatusEnum = {
    Success: 'success',
    Error: 'error'
} as const;
export type CreateSubmissionResponseStatusEnum = typeof CreateSubmissionResponseStatusEnum[keyof typeof CreateSubmissionResponseStatusEnum];


/**
 * Check if a given object implements the CreateSubmissionResponse interface.
 */
export function instanceOfCreateSubmissionResponse(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "status" in value;
    isInstance = isInstance && "submission" in value;

    return isInstance;
}

export function CreateSubmissionResponseFromJSON(json: any): CreateSubmissionResponse {
    return CreateSubmissionResponseFromJSONTyped(json, false);
}

export function CreateSubmissionResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateSubmissionResponse {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'status': json['status'],
        'errors': !exists(json, 'errors') ? undefined : json['errors'],
        'submission': SubmissionFromJSON(json['submission']),
    };
}

export function CreateSubmissionResponseToJSON(value?: CreateSubmissionResponse | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'status': value.status,
        'errors': value.errors,
        'submission': SubmissionToJSON(value.submission),
    };
}

