/* tslint:disable */
/* eslint-disable */
/**
 * API v1
 * DocSpring is a service that helps you fill out and sign PDF templates.
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { Submission } from './Submission';
import {
    SubmissionFromJSON,
    SubmissionFromJSONTyped,
    SubmissionToJSON,
} from './Submission';

/**
 * 
 * @export
 * @interface CreateSubmissionBatchSubmissionsResponse
 */
export interface CreateSubmissionBatchSubmissionsResponse {
    /**
     * 
     * @type {string}
     * @memberof CreateSubmissionBatchSubmissionsResponse
     */
    status: CreateSubmissionBatchSubmissionsResponseStatusEnum;
    /**
     * 
     * @type {Array<string>}
     * @memberof CreateSubmissionBatchSubmissionsResponse
     */
    errors?: Array<string>;
    /**
     * 
     * @type {Submission}
     * @memberof CreateSubmissionBatchSubmissionsResponse
     */
    submission?: Submission;
}


/**
 * @export
 */
export const CreateSubmissionBatchSubmissionsResponseStatusEnum = {
    Success: 'success',
    Error: 'error',
    ValidButNotSaved: 'valid_but_not_saved'
} as const;
export type CreateSubmissionBatchSubmissionsResponseStatusEnum = typeof CreateSubmissionBatchSubmissionsResponseStatusEnum[keyof typeof CreateSubmissionBatchSubmissionsResponseStatusEnum];


/**
 * Check if a given object implements the CreateSubmissionBatchSubmissionsResponse interface.
 */
export function instanceOfCreateSubmissionBatchSubmissionsResponse(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "status" in value;

    return isInstance;
}

export function CreateSubmissionBatchSubmissionsResponseFromJSON(json: any): CreateSubmissionBatchSubmissionsResponse {
    return CreateSubmissionBatchSubmissionsResponseFromJSONTyped(json, false);
}

export function CreateSubmissionBatchSubmissionsResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateSubmissionBatchSubmissionsResponse {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'status': json['status'],
        'errors': !exists(json, 'errors') ? undefined : json['errors'],
        'submission': !exists(json, 'submission') ? undefined : SubmissionFromJSON(json['submission']),
    };
}

export function CreateSubmissionBatchSubmissionsResponseToJSON(value?: CreateSubmissionBatchSubmissionsResponse | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'status': value.status,
        'errors': value.errors,
        'submission': SubmissionToJSON(value.submission),
    };
}

