/* tslint:disable */
/* eslint-disable */
/**
 * API v1
 * DocSpring is a service that helps you fill out and sign PDF templates.
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface DeleteTemplateResponse
 */
export interface DeleteTemplateResponse {
    /**
     * 
     * @type {string}
     * @memberof DeleteTemplateResponse
     */
    status: DeleteTemplateResponseStatusEnum;
    /**
     * 
     * @type {Array<string>}
     * @memberof DeleteTemplateResponse
     */
    errors?: Array<string>;
}


/**
 * @export
 */
export const DeleteTemplateResponseStatusEnum = {
    Success: 'success',
    Error: 'error'
} as const;
export type DeleteTemplateResponseStatusEnum = typeof DeleteTemplateResponseStatusEnum[keyof typeof DeleteTemplateResponseStatusEnum];


/**
 * Check if a given object implements the DeleteTemplateResponse interface.
 */
export function instanceOfDeleteTemplateResponse(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "status" in value;

    return isInstance;
}

export function DeleteTemplateResponseFromJSON(json: any): DeleteTemplateResponse {
    return DeleteTemplateResponseFromJSONTyped(json, false);
}

export function DeleteTemplateResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): DeleteTemplateResponse {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'status': json['status'],
        'errors': !exists(json, 'errors') ? undefined : json['errors'],
    };
}

export function DeleteTemplateResponseToJSON(value?: DeleteTemplateResponse | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'status': value.status,
        'errors': value.errors,
    };
}

