/* tslint:disable */
/* eslint-disable */
/**
 * API v1
 * DocSpring is a service that helps you fill out and sign PDF templates.
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface Folder
 */
export interface Folder {
    /**
     * 
     * @type {string}
     * @memberof Folder
     */
    id?: string;
    /**
     * 
     * @type {string}
     * @memberof Folder
     */
    name?: string;
    /**
     * 
     * @type {string}
     * @memberof Folder
     */
    path?: string;
    /**
     * 
     * @type {string}
     * @memberof Folder
     */
    parentFolderId?: string | null;
}

/**
 * Check if a given object implements the Folder interface.
 */
export function instanceOfFolder(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function FolderFromJSON(json: any): Folder {
    return FolderFromJSONTyped(json, false);
}

export function FolderFromJSONTyped(json: any, ignoreDiscriminator: boolean): Folder {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': !exists(json, 'id') ? undefined : json['id'],
        'name': !exists(json, 'name') ? undefined : json['name'],
        'path': !exists(json, 'path') ? undefined : json['path'],
        'parentFolderId': !exists(json, 'parent_folder_id') ? undefined : json['parent_folder_id'],
    };
}

export function FolderToJSON(value?: Folder | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'id': value.id,
        'name': value.name,
        'path': value.path,
        'parent_folder_id': value.parentFolderId,
    };
}

