/* tslint:disable */
/* eslint-disable */
/**
 * API v1
 * DocSpring is a service that helps you fill out and sign PDF templates.
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface InvalidRequest
 */
export interface InvalidRequest {
    /**
     * 
     * @type {string}
     * @memberof InvalidRequest
     */
    status: InvalidRequestStatusEnum;
    /**
     * 
     * @type {Array<string>}
     * @memberof InvalidRequest
     */
    errors: Array<string>;
}


/**
 * @export
 */
export const InvalidRequestStatusEnum = {
    Error: 'error'
} as const;
export type InvalidRequestStatusEnum = typeof InvalidRequestStatusEnum[keyof typeof InvalidRequestStatusEnum];


/**
 * Check if a given object implements the InvalidRequest interface.
 */
export function instanceOfInvalidRequest(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "status" in value;
    isInstance = isInstance && "errors" in value;

    return isInstance;
}

export function InvalidRequestFromJSON(json: any): InvalidRequest {
    return InvalidRequestFromJSONTyped(json, false);
}

export function InvalidRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): InvalidRequest {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'status': json['status'],
        'errors': json['errors'],
    };
}

export function InvalidRequestToJSON(value?: InvalidRequest | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'status': value.status,
        'errors': value.errors,
    };
}

