/* tslint:disable */
/* eslint-disable */
/**
 * API v1
 * DocSpring is a service that helps you fill out and sign PDF templates.
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface MoveTemplateData
 */
export interface MoveTemplateData {
    /**
     * 
     * @type {string}
     * @memberof MoveTemplateData
     */
    parentFolderId: string;
}

/**
 * Check if a given object implements the MoveTemplateData interface.
 */
export function instanceOfMoveTemplateData(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "parentFolderId" in value;

    return isInstance;
}

export function MoveTemplateDataFromJSON(json: any): MoveTemplateData {
    return MoveTemplateDataFromJSONTyped(json, false);
}

export function MoveTemplateDataFromJSONTyped(json: any, ignoreDiscriminator: boolean): MoveTemplateData {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'parentFolderId': json['parent_folder_id'],
    };
}

export function MoveTemplateDataToJSON(value?: MoveTemplateData | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'parent_folder_id': value.parentFolderId,
    };
}

