/* tslint:disable */
/* eslint-disable */
/**
 * API v1
 * DocSpring is a service that helps you fill out and sign PDF templates.
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface MoveFolderData
 */
export interface MoveFolderData {
    /**
     * 
     * @type {string}
     * @memberof MoveFolderData
     */
    parentFolderId?: string;
}

/**
 * Check if a given object implements the MoveFolderData interface.
 */
export function instanceOfMoveFolderData(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function MoveFolderDataFromJSON(json: any): MoveFolderData {
    return MoveFolderDataFromJSONTyped(json, false);
}

export function MoveFolderDataFromJSONTyped(json: any, ignoreDiscriminator: boolean): MoveFolderData {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'parentFolderId': !exists(json, 'parent_folder_id') ? undefined : json['parent_folder_id'],
    };
}

export function MoveFolderDataToJSON(value?: MoveFolderData | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'parent_folder_id': value.parentFolderId,
    };
}

