/* tslint:disable */
/* eslint-disable */
/**
 * API v1
 * DocSpring is a service that helps you fill out and sign PDF templates.
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface SubmissionDataBatchRequest
 */
export interface SubmissionDataBatchRequest {
    /**
     * 
     * @type {string}
     * @memberof SubmissionDataBatchRequest
     */
    css?: string;
    /**
     * 
     * @type {object}
     * @memberof SubmissionDataBatchRequest
     */
    data: object;
    /**
     * 
     * @type {string}
     * @memberof SubmissionDataBatchRequest
     */
    html?: string;
    /**
     * 
     * @type {object}
     * @memberof SubmissionDataBatchRequest
     */
    metadata?: object;
    /**
     * 
     * @type {string}
     * @memberof SubmissionDataBatchRequest
     */
    templateId: string | null;
    /**
     * 
     * @type {boolean}
     * @memberof SubmissionDataBatchRequest
     */
    test?: boolean;
}

/**
 * Check if a given object implements the SubmissionDataBatchRequest interface.
 */
export function instanceOfSubmissionDataBatchRequest(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "data" in value;
    isInstance = isInstance && "templateId" in value;

    return isInstance;
}

export function SubmissionDataBatchRequestFromJSON(json: any): SubmissionDataBatchRequest {
    return SubmissionDataBatchRequestFromJSONTyped(json, false);
}

export function SubmissionDataBatchRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): SubmissionDataBatchRequest {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'css': !exists(json, 'css') ? undefined : json['css'],
        'data': json['data'],
        'html': !exists(json, 'html') ? undefined : json['html'],
        'metadata': !exists(json, 'metadata') ? undefined : json['metadata'],
        'templateId': json['template_id'],
        'test': !exists(json, 'test') ? undefined : json['test'],
    };
}

export function SubmissionDataBatchRequestToJSON(value?: SubmissionDataBatchRequest | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'css': value.css,
        'data': value.data,
        'html': value.html,
        'metadata': value.metadata,
        'template_id': value.templateId,
        'test': value.test,
    };
}

