/* tslint:disable */
/* eslint-disable */
/**
 * API v1
 * DocSpring is a service that helps you fill out and sign PDF templates.
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { CreateSubmissionDataRequestData } from './CreateSubmissionDataRequestData';
import {
    CreateSubmissionDataRequestDataFromJSON,
    CreateSubmissionDataRequestDataFromJSONTyped,
    CreateSubmissionDataRequestDataToJSON,
} from './CreateSubmissionDataRequestData';

/**
 * 
 * @export
 * @interface SubmissionData
 */
export interface SubmissionData {
    /**
     * 
     * @type {string}
     * @memberof SubmissionData
     */
    css?: string;
    /**
     * 
     * @type {object}
     * @memberof SubmissionData
     */
    data: object;
    /**
     * 
     * @type {Array<CreateSubmissionDataRequestData>}
     * @memberof SubmissionData
     */
    dataRequests?: Array<CreateSubmissionDataRequestData>;
    /**
     * 
     * @type {string}
     * @memberof SubmissionData
     */
    html?: string;
    /**
     * 
     * @type {object}
     * @memberof SubmissionData
     */
    metadata?: object;
    /**
     * 
     * @type {boolean}
     * @memberof SubmissionData
     */
    test?: boolean;
}

/**
 * Check if a given object implements the SubmissionData interface.
 */
export function instanceOfSubmissionData(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "data" in value;

    return isInstance;
}

export function SubmissionDataFromJSON(json: any): SubmissionData {
    return SubmissionDataFromJSONTyped(json, false);
}

export function SubmissionDataFromJSONTyped(json: any, ignoreDiscriminator: boolean): SubmissionData {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'css': !exists(json, 'css') ? undefined : json['css'],
        'data': json['data'],
        'dataRequests': !exists(json, 'data_requests') ? undefined : ((json['data_requests'] as Array<any>).map(CreateSubmissionDataRequestDataFromJSON)),
        'html': !exists(json, 'html') ? undefined : json['html'],
        'metadata': !exists(json, 'metadata') ? undefined : json['metadata'],
        'test': !exists(json, 'test') ? undefined : json['test'],
    };
}

export function SubmissionDataToJSON(value?: SubmissionData | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'css': value.css,
        'data': value.data,
        'data_requests': value.dataRequests === undefined ? undefined : ((value.dataRequests as Array<any>).map(CreateSubmissionDataRequestDataToJSON)),
        'html': value.html,
        'metadata': value.metadata,
        'test': value.test,
    };
}

