/* tslint:disable */
/* eslint-disable */
/**
 * API v1
 * DocSpring is a service that helps you fill out and sign PDF templates.
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface SubmissionAction
 */
export interface SubmissionAction {
    /**
     * 
     * @type {string}
     * @memberof SubmissionAction
     */
    id: string;
    /**
     * 
     * @type {string}
     * @memberof SubmissionAction
     */
    integrationId: string | null;
    /**
     * 
     * @type {string}
     * @memberof SubmissionAction
     */
    state: SubmissionActionStateEnum;
    /**
     * 
     * @type {string}
     * @memberof SubmissionAction
     */
    actionCategory: SubmissionActionActionCategoryEnum;
    /**
     * 
     * @type {string}
     * @memberof SubmissionAction
     */
    actionType: SubmissionActionActionTypeEnum;
    /**
     * 
     * @type {object}
     * @memberof SubmissionAction
     */
    resultData: object;
}


/**
 * @export
 */
export const SubmissionActionStateEnum = {
    Pending: 'pending',
    Processed: 'processed',
    Failed: 'failed',
    Error: 'error'
} as const;
export type SubmissionActionStateEnum = typeof SubmissionActionStateEnum[keyof typeof SubmissionActionStateEnum];

/**
 * @export
 */
export const SubmissionActionActionCategoryEnum = {
    Notification: 'notification',
    FileUpload: 'file_upload'
} as const;
export type SubmissionActionActionCategoryEnum = typeof SubmissionActionActionCategoryEnum[keyof typeof SubmissionActionActionCategoryEnum];

/**
 * @export
 */
export const SubmissionActionActionTypeEnum = {
    Webhook: 'webhook',
    SlackWebhook: 'slack_webhook',
    Email: 'email',
    AwsS3Upload: 'aws_s3_upload'
} as const;
export type SubmissionActionActionTypeEnum = typeof SubmissionActionActionTypeEnum[keyof typeof SubmissionActionActionTypeEnum];


/**
 * Check if a given object implements the SubmissionAction interface.
 */
export function instanceOfSubmissionAction(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "id" in value;
    isInstance = isInstance && "integrationId" in value;
    isInstance = isInstance && "state" in value;
    isInstance = isInstance && "actionCategory" in value;
    isInstance = isInstance && "actionType" in value;
    isInstance = isInstance && "resultData" in value;

    return isInstance;
}

export function SubmissionActionFromJSON(json: any): SubmissionAction {
    return SubmissionActionFromJSONTyped(json, false);
}

export function SubmissionActionFromJSONTyped(json: any, ignoreDiscriminator: boolean): SubmissionAction {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': json['id'],
        'integrationId': json['integration_id'],
        'state': json['state'],
        'actionCategory': json['action_category'],
        'actionType': json['action_type'],
        'resultData': json['result_data'],
    };
}

export function SubmissionActionToJSON(value?: SubmissionAction | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'id': value.id,
        'integration_id': value.integrationId,
        'state': value.state,
        'action_category': value.actionCategory,
        'action_type': value.actionType,
        'result_data': value.resultData,
    };
}

