/* tslint:disable */
/* eslint-disable */
/**
 * API v1
 * DocSpring is a service that helps you fill out and sign PDF templates.
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface Template
 */
export interface Template {
    /**
     * 
     * @type {string}
     * @memberof Template
     */
    name: string | null;
    /**
     * 
     * @type {string}
     * @memberof Template
     */
    description: string | null;
    /**
     * 
     * @type {boolean}
     * @memberof Template
     */
    publicWebForm: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof Template
     */
    publicSubmissions: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof Template
     */
    expireSubmissions: boolean;
    /**
     * 
     * @type {number}
     * @memberof Template
     */
    expireAfter: number;
    /**
     * 
     * @type {string}
     * @memberof Template
     */
    expirationInterval: TemplateExpirationIntervalEnum;
    /**
     * 
     * @type {boolean}
     * @memberof Template
     */
    allowAdditionalProperties: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof Template
     */
    editableSubmissions: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof Template
     */
    locked: boolean;
    /**
     * 
     * @type {string}
     * @memberof Template
     */
    webhookUrl: string | null;
    /**
     * 
     * @type {string}
     * @memberof Template
     */
    slackWebhookUrl: string | null;
    /**
     * 
     * @type {string}
     * @memberof Template
     */
    redirectUrl: string | null;
    /**
     * 
     * @type {string}
     * @memberof Template
     */
    id: string;
    /**
     * 
     * @type {string}
     * @memberof Template
     */
    templateType: string;
    /**
     * 
     * @type {Array<Array<number>>}
     * @memberof Template
     */
    pageDimensions: Array<Array<number>> | null;
    /**
     * 
     * @type {string}
     * @memberof Template
     */
    documentUrl: string | null;
    /**
     * 
     * @type {string}
     * @memberof Template
     */
    permanentDocumentUrl: string | null;
    /**
     * 
     * @type {string}
     * @memberof Template
     */
    path: string;
    /**
     * 
     * @type {string}
     * @memberof Template
     */
    parentFolderId: string | null;
}


/**
 * @export
 */
export const TemplateExpirationIntervalEnum = {
    Minutes: 'minutes',
    Hours: 'hours',
    Days: 'days'
} as const;
export type TemplateExpirationIntervalEnum = typeof TemplateExpirationIntervalEnum[keyof typeof TemplateExpirationIntervalEnum];


/**
 * Check if a given object implements the Template interface.
 */
export function instanceOfTemplate(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "name" in value;
    isInstance = isInstance && "description" in value;
    isInstance = isInstance && "publicWebForm" in value;
    isInstance = isInstance && "publicSubmissions" in value;
    isInstance = isInstance && "expireSubmissions" in value;
    isInstance = isInstance && "expireAfter" in value;
    isInstance = isInstance && "expirationInterval" in value;
    isInstance = isInstance && "allowAdditionalProperties" in value;
    isInstance = isInstance && "editableSubmissions" in value;
    isInstance = isInstance && "locked" in value;
    isInstance = isInstance && "webhookUrl" in value;
    isInstance = isInstance && "slackWebhookUrl" in value;
    isInstance = isInstance && "redirectUrl" in value;
    isInstance = isInstance && "id" in value;
    isInstance = isInstance && "templateType" in value;
    isInstance = isInstance && "pageDimensions" in value;
    isInstance = isInstance && "documentUrl" in value;
    isInstance = isInstance && "permanentDocumentUrl" in value;
    isInstance = isInstance && "path" in value;
    isInstance = isInstance && "parentFolderId" in value;

    return isInstance;
}

export function TemplateFromJSON(json: any): Template {
    return TemplateFromJSONTyped(json, false);
}

export function TemplateFromJSONTyped(json: any, ignoreDiscriminator: boolean): Template {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'name': json['name'],
        'description': json['description'],
        'publicWebForm': json['public_web_form'],
        'publicSubmissions': json['public_submissions'],
        'expireSubmissions': json['expire_submissions'],
        'expireAfter': json['expire_after'],
        'expirationInterval': json['expiration_interval'],
        'allowAdditionalProperties': json['allow_additional_properties'],
        'editableSubmissions': json['editable_submissions'],
        'locked': json['locked'],
        'webhookUrl': json['webhook_url'],
        'slackWebhookUrl': json['slack_webhook_url'],
        'redirectUrl': json['redirect_url'],
        'id': json['id'],
        'templateType': json['template_type'],
        'pageDimensions': json['page_dimensions'],
        'documentUrl': json['document_url'],
        'permanentDocumentUrl': json['permanent_document_url'],
        'path': json['path'],
        'parentFolderId': json['parent_folder_id'],
    };
}

export function TemplateToJSON(value?: Template | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'name': value.name,
        'description': value.description,
        'public_web_form': value.publicWebForm,
        'public_submissions': value.publicSubmissions,
        'expire_submissions': value.expireSubmissions,
        'expire_after': value.expireAfter,
        'expiration_interval': value.expirationInterval,
        'allow_additional_properties': value.allowAdditionalProperties,
        'editable_submissions': value.editableSubmissions,
        'locked': value.locked,
        'webhook_url': value.webhookUrl,
        'slack_webhook_url': value.slackWebhookUrl,
        'redirect_url': value.redirectUrl,
        'id': value.id,
        'template_type': value.templateType,
        'page_dimensions': value.pageDimensions,
        'document_url': value.documentUrl,
        'permanent_document_url': value.permanentDocumentUrl,
        'path': value.path,
        'parent_folder_id': value.parentFolderId,
    };
}

