/* tslint:disable */
/* eslint-disable */
/**
 * API v1
 * DocSpring is a service that helps you fill out and sign PDF templates.
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface TemplateData
 */
export interface TemplateData {
    /**
     * 
     * @type {boolean}
     * @memberof TemplateData
     */
    allowAdditionalProperties?: boolean;
    /**
     * 
     * @type {string}
     * @memberof TemplateData
     */
    description?: string | null;
    /**
     * 
     * @type {boolean}
     * @memberof TemplateData
     */
    editableSubmissions?: boolean;
    /**
     * 
     * @type {string}
     * @memberof TemplateData
     */
    expirationInterval?: TemplateDataExpirationIntervalEnum;
    /**
     * 
     * @type {number}
     * @memberof TemplateData
     */
    expireAfter?: number;
    /**
     * 
     * @type {boolean}
     * @memberof TemplateData
     */
    expireSubmissions?: boolean;
    /**
     * 
     * @type {string}
     * @memberof TemplateData
     */
    footerHtml?: string | null;
    /**
     * 
     * @type {string}
     * @memberof TemplateData
     */
    headerHtml?: string | null;
    /**
     * 
     * @type {string}
     * @memberof TemplateData
     */
    html?: string | null;
    /**
     * 
     * @type {string}
     * @memberof TemplateData
     */
    name?: string | null;
    /**
     * 
     * @type {boolean}
     * @memberof TemplateData
     */
    publicSubmissions?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof TemplateData
     */
    publicWebForm?: boolean;
    /**
     * 
     * @type {string}
     * @memberof TemplateData
     */
    redirectUrl?: string | null;
    /**
     * 
     * @type {string}
     * @memberof TemplateData
     */
    scss?: string | null;
    /**
     * 
     * @type {string}
     * @memberof TemplateData
     */
    slackWebhookUrl?: string | null;
    /**
     * 
     * @type {string}
     * @memberof TemplateData
     */
    webhookUrl?: string | null;
}


/**
 * @export
 */
export const TemplateDataExpirationIntervalEnum = {
    Minutes: 'minutes',
    Hours: 'hours',
    Days: 'days'
} as const;
export type TemplateDataExpirationIntervalEnum = typeof TemplateDataExpirationIntervalEnum[keyof typeof TemplateDataExpirationIntervalEnum];


/**
 * Check if a given object implements the TemplateData interface.
 */
export function instanceOfTemplateData(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function TemplateDataFromJSON(json: any): TemplateData {
    return TemplateDataFromJSONTyped(json, false);
}

export function TemplateDataFromJSONTyped(json: any, ignoreDiscriminator: boolean): TemplateData {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'allowAdditionalProperties': !exists(json, 'allow_additional_properties') ? undefined : json['allow_additional_properties'],
        'description': !exists(json, 'description') ? undefined : json['description'],
        'editableSubmissions': !exists(json, 'editable_submissions') ? undefined : json['editable_submissions'],
        'expirationInterval': !exists(json, 'expiration_interval') ? undefined : json['expiration_interval'],
        'expireAfter': !exists(json, 'expire_after') ? undefined : json['expire_after'],
        'expireSubmissions': !exists(json, 'expire_submissions') ? undefined : json['expire_submissions'],
        'footerHtml': !exists(json, 'footer_html') ? undefined : json['footer_html'],
        'headerHtml': !exists(json, 'header_html') ? undefined : json['header_html'],
        'html': !exists(json, 'html') ? undefined : json['html'],
        'name': !exists(json, 'name') ? undefined : json['name'],
        'publicSubmissions': !exists(json, 'public_submissions') ? undefined : json['public_submissions'],
        'publicWebForm': !exists(json, 'public_web_form') ? undefined : json['public_web_form'],
        'redirectUrl': !exists(json, 'redirect_url') ? undefined : json['redirect_url'],
        'scss': !exists(json, 'scss') ? undefined : json['scss'],
        'slackWebhookUrl': !exists(json, 'slack_webhook_url') ? undefined : json['slack_webhook_url'],
        'webhookUrl': !exists(json, 'webhook_url') ? undefined : json['webhook_url'],
    };
}

export function TemplateDataToJSON(value?: TemplateData | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'allow_additional_properties': value.allowAdditionalProperties,
        'description': value.description,
        'editable_submissions': value.editableSubmissions,
        'expiration_interval': value.expirationInterval,
        'expire_after': value.expireAfter,
        'expire_submissions': value.expireSubmissions,
        'footer_html': value.footerHtml,
        'header_html': value.headerHtml,
        'html': value.html,
        'name': value.name,
        'public_submissions': value.publicSubmissions,
        'public_web_form': value.publicWebForm,
        'redirect_url': value.redirectUrl,
        'scss': value.scss,
        'slack_webhook_url': value.slackWebhookUrl,
        'webhook_url': value.webhookUrl,
    };
}

