/* tslint:disable */
/* eslint-disable */
/**
 * API v1
 * DocSpring is a service that helps you fill out and sign PDF templates.
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface TemplateDefaults
 */
export interface TemplateDefaults {
    /**
     * 
     * @type {string}
     * @memberof TemplateDefaults
     */
    color: string | null;
    /**
     * 
     * @type {number}
     * @memberof TemplateDefaults
     */
    fontSize: number;
    /**
     * 
     * @type {string}
     * @memberof TemplateDefaults
     */
    typeface: string;
}

/**
 * Check if a given object implements the TemplateDefaults interface.
 */
export function instanceOfTemplateDefaults(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "color" in value;
    isInstance = isInstance && "fontSize" in value;
    isInstance = isInstance && "typeface" in value;

    return isInstance;
}

export function TemplateDefaultsFromJSON(json: any): TemplateDefaults {
    return TemplateDefaultsFromJSONTyped(json, false);
}

export function TemplateDefaultsFromJSONTyped(json: any, ignoreDiscriminator: boolean): TemplateDefaults {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'color': json['color'],
        'fontSize': json['fontSize'],
        'typeface': json['typeface'],
    };
}

export function TemplateDefaultsToJSON(value?: TemplateDefaults | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'color': value.color,
        'fontSize': value.fontSize,
        'typeface': value.typeface,
    };
}

