/* tslint:disable */
/* eslint-disable */
/**
 * API v1
 * DocSpring is a service that helps you fill out and sign PDF templates.
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { TemplateData } from './TemplateData';
import {
    TemplateDataFromJSON,
    TemplateDataFromJSONTyped,
    TemplateDataToJSON,
} from './TemplateData';

/**
 * 
 * @export
 * @interface UpdateTemplateData
 */
export interface UpdateTemplateData {
    /**
     * 
     * @type {TemplateData}
     * @memberof UpdateTemplateData
     */
    template: TemplateData;
}

/**
 * Check if a given object implements the UpdateTemplateData interface.
 */
export function instanceOfUpdateTemplateData(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "template" in value;

    return isInstance;
}

export function UpdateTemplateDataFromJSON(json: any): UpdateTemplateData {
    return UpdateTemplateDataFromJSONTyped(json, false);
}

export function UpdateTemplateDataFromJSONTyped(json: any, ignoreDiscriminator: boolean): UpdateTemplateData {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'template': TemplateDataFromJSON(json['template']),
    };
}

export function UpdateTemplateDataToJSON(value?: UpdateTemplateData | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'template': TemplateDataToJSON(value.template),
    };
}

