/**
 * DocSpring API
 * DocSpring provides an API that helps you fill out and sign PDF templates.
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { SubmissionBatch } from '../models/SubmissionBatch';
import { HttpFile } from '../http/http';

export class BatchGeneratePdfs201Response {
    'status': BatchGeneratePdfs201ResponseStatusEnum;
    'error'?: string;
    'errors'?: Array<string>;
    'submissionBatch': SubmissionBatch;
    'submissions': Array<any>;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "status",
            "baseName": "status",
            "type": "BatchGeneratePdfs201ResponseStatusEnum",
            "format": ""
        },
        {
            "name": "error",
            "baseName": "error",
            "type": "string",
            "format": ""
        },
        {
            "name": "errors",
            "baseName": "errors",
            "type": "Array<string>",
            "format": ""
        },
        {
            "name": "submissionBatch",
            "baseName": "submission_batch",
            "type": "SubmissionBatch",
            "format": ""
        },
        {
            "name": "submissions",
            "baseName": "submissions",
            "type": "Array<any>",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return BatchGeneratePdfs201Response.attributeTypeMap;
    }

    public constructor() {
    }
}

export enum BatchGeneratePdfs201ResponseStatusEnum {
    Success = 'success',
    Error = 'error'
}

