/**
 * DocSpring API
 * Use DocSpring\'s API to programmatically fill out PDF forms, convert HTML to PDFs, merge PDFs, or request legally binding e-signatures.
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

export class CombinePdfsData {
    'delete_custom_files'?: boolean;
    'expires_in'?: number;
    'metadata'?: any;
    'password'?: string;
    'source_pdfs': Array<any>;
    'test'?: boolean;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "delete_custom_files",
            "baseName": "delete_custom_files",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "expires_in",
            "baseName": "expires_in",
            "type": "number",
            "format": ""
        },
        {
            "name": "metadata",
            "baseName": "metadata",
            "type": "any",
            "format": ""
        },
        {
            "name": "password",
            "baseName": "password",
            "type": "string",
            "format": ""
        },
        {
            "name": "source_pdfs",
            "baseName": "source_pdfs",
            "type": "Array<any>",
            "format": ""
        },
        {
            "name": "test",
            "baseName": "test",
            "type": "boolean",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return CombinePdfsData.attributeTypeMap;
    }

    public constructor() {
    }
}
