/**
 * DocSpring API
 * Use DocSpring\'s API to programmatically fill out PDF forms, convert HTML to PDFs, merge PDFs, or request legally binding e-signatures.
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { CombinedSubmissionAction } from '../models/CombinedSubmissionAction';
import { HttpFile } from '../http/http';

export class CombinedSubmission {
    'id': string | null;
    'state': CombinedSubmissionStateEnum;
    'expired': boolean;
    'expires_in': number | null;
    'expires_at': string | null;
    'processed_at': string | null;
    'error_message': string | null;
    'submission_ids': Array<string>;
    'source_pdfs': Array<any>;
    'metadata': any;
    'password': string | null;
    'pdf_hash': string | null;
    'download_url': string | null;
    'actions': Array<CombinedSubmissionAction>;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "id",
            "baseName": "id",
            "type": "string",
            "format": ""
        },
        {
            "name": "state",
            "baseName": "state",
            "type": "CombinedSubmissionStateEnum",
            "format": ""
        },
        {
            "name": "expired",
            "baseName": "expired",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "expires_in",
            "baseName": "expires_in",
            "type": "number",
            "format": ""
        },
        {
            "name": "expires_at",
            "baseName": "expires_at",
            "type": "string",
            "format": ""
        },
        {
            "name": "processed_at",
            "baseName": "processed_at",
            "type": "string",
            "format": ""
        },
        {
            "name": "error_message",
            "baseName": "error_message",
            "type": "string",
            "format": ""
        },
        {
            "name": "submission_ids",
            "baseName": "submission_ids",
            "type": "Array<string>",
            "format": ""
        },
        {
            "name": "source_pdfs",
            "baseName": "source_pdfs",
            "type": "Array<any>",
            "format": ""
        },
        {
            "name": "metadata",
            "baseName": "metadata",
            "type": "any",
            "format": ""
        },
        {
            "name": "password",
            "baseName": "password",
            "type": "string",
            "format": ""
        },
        {
            "name": "pdf_hash",
            "baseName": "pdf_hash",
            "type": "string",
            "format": ""
        },
        {
            "name": "download_url",
            "baseName": "download_url",
            "type": "string",
            "format": ""
        },
        {
            "name": "actions",
            "baseName": "actions",
            "type": "Array<CombinedSubmissionAction>",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return CombinedSubmission.attributeTypeMap;
    }

    public constructor() {
    }
}

export enum CombinedSubmissionStateEnum {
    Pending = 'pending',
    Processed = 'processed',
    Error = 'error'
}

