/**
 * DocSpring API
 * Use DocSpring\'s API to programmatically fill out PDF forms, convert HTML to PDFs, merge PDFs, or request legally binding e-signatures.
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

export class CombinedSubmissionAction {
    'id': string | null;
    'integration_id': string | null;
    'state': CombinedSubmissionActionStateEnum;
    'action_type': CombinedSubmissionActionActionTypeEnum | null;
    'action_category': CombinedSubmissionActionActionCategoryEnum;
    'result_data': any;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "id",
            "baseName": "id",
            "type": "string",
            "format": ""
        },
        {
            "name": "integration_id",
            "baseName": "integration_id",
            "type": "string",
            "format": ""
        },
        {
            "name": "state",
            "baseName": "state",
            "type": "CombinedSubmissionActionStateEnum",
            "format": ""
        },
        {
            "name": "action_type",
            "baseName": "action_type",
            "type": "CombinedSubmissionActionActionTypeEnum",
            "format": ""
        },
        {
            "name": "action_category",
            "baseName": "action_category",
            "type": "CombinedSubmissionActionActionCategoryEnum",
            "format": ""
        },
        {
            "name": "result_data",
            "baseName": "result_data",
            "type": "any",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return CombinedSubmissionAction.attributeTypeMap;
    }

    public constructor() {
    }
}

export enum CombinedSubmissionActionStateEnum {
    Pending = 'pending',
    Processed = 'processed',
    Failed = 'failed',
    Error = 'error'
}
export enum CombinedSubmissionActionActionTypeEnum {
    Webhook = 'webhook',
    SlackWebhook = 'slack_webhook',
    Email = 'email',
    AwsS3Upload = 'aws_s3_upload'
}
export enum CombinedSubmissionActionActionCategoryEnum {
    Notification = 'notification',
    FileUpload = 'file_upload'
}

