/**
 * DocSpring API
 * Use DocSpring\'s API to programmatically fill out PDF forms, convert HTML to PDFs, merge PDFs, or request legally binding e-signatures.
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { CombinedSubmission } from '../models/CombinedSubmission';
import { HttpFile } from '../http/http';

export class CreateCombinedSubmissionResponse {
    'status': CreateCombinedSubmissionResponseStatusEnum;
    'combined_submission': CombinedSubmission;
    'errors'?: Array<string>;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "status",
            "baseName": "status",
            "type": "CreateCombinedSubmissionResponseStatusEnum",
            "format": ""
        },
        {
            "name": "combined_submission",
            "baseName": "combined_submission",
            "type": "CombinedSubmission",
            "format": ""
        },
        {
            "name": "errors",
            "baseName": "errors",
            "type": "Array<string>",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return CreateCombinedSubmissionResponse.attributeTypeMap;
    }

    public constructor() {
    }
}

export enum CreateCombinedSubmissionResponseStatusEnum {
    Success = 'success',
    Error = 'error'
}

