/**
 * DocSpring API
 * DocSpring provides an API that helps you fill out and sign PDF templates.
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { CreateSubmissionDataRequestData } from '../models/CreateSubmissionDataRequestData';
import { HttpFile } from '../http/http';

export class CreatePdfSubmissionData {
    'data': any;
    'dataRequests'?: Array<CreateSubmissionDataRequestData>;
    'editable'?: boolean;
    'expiresIn'?: number;
    'fieldOverrides'?: any;
    'metadata'?: any;
    'password'?: string;
    'test'?: boolean;
    'version'?: string;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "data",
            "baseName": "data",
            "type": "any",
            "format": ""
        },
        {
            "name": "dataRequests",
            "baseName": "data_requests",
            "type": "Array<CreateSubmissionDataRequestData>",
            "format": ""
        },
        {
            "name": "editable",
            "baseName": "editable",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "expiresIn",
            "baseName": "expires_in",
            "type": "number",
            "format": ""
        },
        {
            "name": "fieldOverrides",
            "baseName": "field_overrides",
            "type": "any",
            "format": ""
        },
        {
            "name": "metadata",
            "baseName": "metadata",
            "type": "any",
            "format": ""
        },
        {
            "name": "password",
            "baseName": "password",
            "type": "string",
            "format": ""
        },
        {
            "name": "test",
            "baseName": "test",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "version",
            "baseName": "version",
            "type": "string",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return CreatePdfSubmissionData.attributeTypeMap;
    }

    public constructor() {
    }
}
