/**
 * DocSpring API
 * Use DocSpring\'s API to programmatically fill out PDF forms, convert HTML to PDFs, merge PDFs, or request legally binding e-signatures.
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { CustomFile } from '../models/CustomFile';
import { HttpFile } from '../http/http';

export class CreateCustomFileResponse {
    'status': CreateCustomFileResponseStatusEnum;
    'custom_file': CustomFile;
    'errors'?: Array<string>;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "status",
            "baseName": "status",
            "type": "CreateCustomFileResponseStatusEnum",
            "format": ""
        },
        {
            "name": "custom_file",
            "baseName": "custom_file",
            "type": "CustomFile",
            "format": ""
        },
        {
            "name": "errors",
            "baseName": "errors",
            "type": "Array<string>",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return CreateCustomFileResponse.attributeTypeMap;
    }

    public constructor() {
    }
}

export enum CreateCustomFileResponseStatusEnum {
    Success = 'success',
    Error = 'error'
}

