/**
 * DocSpring API
 * DocSpring provides an API that helps you fill out and sign PDF templates.
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { SubmissionPreview } from '../models/SubmissionPreview';
import { HttpFile } from '../http/http';

export class CreateSubmissionResponse {
    'status': CreateSubmissionResponseStatusEnum;
    'submission': SubmissionPreview;
    'errors'?: Array<string>;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "status",
            "baseName": "status",
            "type": "CreateSubmissionResponseStatusEnum",
            "format": ""
        },
        {
            "name": "submission",
            "baseName": "submission",
            "type": "SubmissionPreview",
            "format": ""
        },
        {
            "name": "errors",
            "baseName": "errors",
            "type": "Array<string>",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return CreateSubmissionResponse.attributeTypeMap;
    }

    public constructor() {
    }
}

export enum CreateSubmissionResponseStatusEnum {
    Success = 'success',
    Error = 'error'
}

