/**
 * DocSpring API
 * DocSpring provides an API that helps you fill out and sign PDF templates.
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { SubmissionDataRequestShow } from '../models/SubmissionDataRequestShow';
import { HttpFile } from '../http/http';

export class CreateSubmissionDataRequestResponse {
    'status': CreateSubmissionDataRequestResponseStatusEnum;
    'dataRequest': SubmissionDataRequestShow;
    'errors'?: Array<string>;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "status",
            "baseName": "status",
            "type": "CreateSubmissionDataRequestResponseStatusEnum",
            "format": ""
        },
        {
            "name": "dataRequest",
            "baseName": "data_request",
            "type": "SubmissionDataRequestShow",
            "format": ""
        },
        {
            "name": "errors",
            "baseName": "errors",
            "type": "Array<string>",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return CreateSubmissionDataRequestResponse.attributeTypeMap;
    }

    public constructor() {
    }
}

export enum CreateSubmissionDataRequestResponseStatusEnum {
    Success = 'success',
    Error = 'error'
}

