/**
 * DocSpring API
 * Use DocSpring\'s API to programmatically fill out PDF forms, convert HTML to PDFs, merge PDFs, or request legally binding e-signatures.
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { SubmissionDataRequestToken } from '../models/SubmissionDataRequestToken';
import { HttpFile } from '../http/http';

export class CreateSubmissionDataRequestTokenResponse {
    'status': CreateSubmissionDataRequestTokenResponseStatusEnum;
    'token': SubmissionDataRequestToken;
    'errors'?: Array<string>;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "status",
            "baseName": "status",
            "type": "CreateSubmissionDataRequestTokenResponseStatusEnum",
            "format": ""
        },
        {
            "name": "token",
            "baseName": "token",
            "type": "SubmissionDataRequestToken",
            "format": ""
        },
        {
            "name": "errors",
            "baseName": "errors",
            "type": "Array<string>",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return CreateSubmissionDataRequestTokenResponse.attributeTypeMap;
    }

    public constructor() {
    }
}

export enum CreateSubmissionDataRequestTokenResponseStatusEnum {
    Success = 'success',
    Error = 'error'
}

