/**
 * DocSpring API
 * Use DocSpring\'s API to programmatically fill out PDF forms, convert HTML to PDFs, merge PDFs, or request legally binding e-signatures.
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { CreateSubmissionDataRequestData } from '../models/CreateSubmissionDataRequestData';
import { HttpFile } from '../http/http';

export class CreatePdfSubmissionData {
    'data': any;
    'data_requests'?: Array<CreateSubmissionDataRequestData>;
    'editable'?: boolean;
    'expires_in'?: number;
    'field_overrides'?: any;
    'metadata'?: any;
    'password'?: string;
    'test'?: boolean;
    'version'?: string;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "data",
            "baseName": "data",
            "type": "any",
            "format": ""
        },
        {
            "name": "data_requests",
            "baseName": "data_requests",
            "type": "Array<CreateSubmissionDataRequestData>",
            "format": ""
        },
        {
            "name": "editable",
            "baseName": "editable",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "expires_in",
            "baseName": "expires_in",
            "type": "number",
            "format": ""
        },
        {
            "name": "field_overrides",
            "baseName": "field_overrides",
            "type": "any",
            "format": ""
        },
        {
            "name": "metadata",
            "baseName": "metadata",
            "type": "any",
            "format": ""
        },
        {
            "name": "password",
            "baseName": "password",
            "type": "string",
            "format": ""
        },
        {
            "name": "test",
            "baseName": "test",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "version",
            "baseName": "version",
            "type": "string",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return CreatePdfSubmissionData.attributeTypeMap;
    }

    public constructor() {
    }
}
