/**
 * DocSpring API
 * DocSpring provides an API that helps you fill out and sign PDF templates.
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

export class CreateSubmissionDataRequestEventRequest {
    'eventType': CreateSubmissionDataRequestEventRequestEventTypeEnum;
    'messageType'?: CreateSubmissionDataRequestEventRequestMessageTypeEnum | null;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "eventType",
            "baseName": "event_type",
            "type": "CreateSubmissionDataRequestEventRequestEventTypeEnum",
            "format": ""
        },
        {
            "name": "messageType",
            "baseName": "message_type",
            "type": "CreateSubmissionDataRequestEventRequestMessageTypeEnum",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return CreateSubmissionDataRequestEventRequest.attributeTypeMap;
    }

    public constructor() {
    }
}

export enum CreateSubmissionDataRequestEventRequestEventTypeEnum {
    SendRequest = 'send_request',
    ViewRequest = 'view_request',
    AcceptedTerms = 'accepted_terms',
    DeclineRequest = 'decline_request',
    SignRequest = 'sign_request',
    AllCompleted = 'all_completed'
}
export enum CreateSubmissionDataRequestEventRequestMessageTypeEnum {
    Email = 'email',
    Sms = 'sms',
    Fax = 'fax',
    Mail = 'mail',
    Slack = 'slack',
    Msteams = 'msteams',
    Discord = 'discord',
    Telegram = 'telegram',
    Whatsapp = 'whatsapp'
}

