/**
 * DocSpring API
 * Use DocSpring\'s API to programmatically fill out PDF forms, convert HTML to PDFs, merge PDFs, or request legally binding e-signatures.
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

export class CreateSubmissionDataRequestEventRequest {
    'event_type': CreateSubmissionDataRequestEventRequestEventTypeEnum;
    'message_recipient'?: string | null;
    'message_type'?: CreateSubmissionDataRequestEventRequestMessageTypeEnum | null;
    'occurred_at'?: string | null;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "event_type",
            "baseName": "event_type",
            "type": "CreateSubmissionDataRequestEventRequestEventTypeEnum",
            "format": ""
        },
        {
            "name": "message_recipient",
            "baseName": "message_recipient",
            "type": "string",
            "format": ""
        },
        {
            "name": "message_type",
            "baseName": "message_type",
            "type": "CreateSubmissionDataRequestEventRequestMessageTypeEnum",
            "format": ""
        },
        {
            "name": "occurred_at",
            "baseName": "occurred_at",
            "type": "string",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return CreateSubmissionDataRequestEventRequest.attributeTypeMap;
    }

    public constructor() {
    }
}

export enum CreateSubmissionDataRequestEventRequestEventTypeEnum {
    SendRequest = 'send_request',
    ViewRequest = 'view_request',
    AcceptedTerms = 'accepted_terms',
    DeclineRequest = 'decline_request',
    SignRequest = 'sign_request',
    AllCompleted = 'all_completed'
}
export enum CreateSubmissionDataRequestEventRequestMessageTypeEnum {
    Email = 'email',
    Sms = 'sms',
    Fax = 'fax',
    Mail = 'mail',
    Slack = 'slack',
    Msteams = 'msteams',
    Discord = 'discord',
    Telegram = 'telegram',
    Whatsapp = 'whatsapp'
}

