/**
 * DocSpring API
 * Use DocSpring\'s API to programmatically fill out PDF forms, convert HTML to PDFs, merge PDFs, or request legally binding e-signatures.
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

export class ErrorOrMultipleErrorsResponse {
    'status': ErrorOrMultipleErrorsResponseStatusEnum;
    /**
    * Single error message (when only one error occurred)
    */
    'error'?: string;
    /**
    * Array of error messages (when multiple validation errors occurred)
    */
    'errors'?: Array<string>;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "status",
            "baseName": "status",
            "type": "ErrorOrMultipleErrorsResponseStatusEnum",
            "format": ""
        },
        {
            "name": "error",
            "baseName": "error",
            "type": "string",
            "format": ""
        },
        {
            "name": "errors",
            "baseName": "errors",
            "type": "Array<string>",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return ErrorOrMultipleErrorsResponse.attributeTypeMap;
    }

    public constructor() {
    }
}

export enum ErrorOrMultipleErrorsResponseStatusEnum {
    Error = 'error'
}

