/**
 * DocSpring API
 * Use DocSpring\'s API to programmatically fill out PDF forms, convert HTML to PDFs, merge PDFs, or request legally binding e-signatures.
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

export class JsonSchema {
    'schema'?: string;
    'id'?: string;
    'title'?: string;
    'description'?: string;
    'definitions'?: any;
    'type'?: string;
    'properties'?: any;
    'additionalProperties'?: boolean;
    'required'?: Array<string>;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "schema",
            "baseName": "$schema",
            "type": "string",
            "format": "uri"
        },
        {
            "name": "id",
            "baseName": "id",
            "type": "string",
            "format": "uri-reference"
        },
        {
            "name": "title",
            "baseName": "title",
            "type": "string",
            "format": ""
        },
        {
            "name": "description",
            "baseName": "description",
            "type": "string",
            "format": ""
        },
        {
            "name": "definitions",
            "baseName": "definitions",
            "type": "any",
            "format": ""
        },
        {
            "name": "type",
            "baseName": "type",
            "type": "string",
            "format": ""
        },
        {
            "name": "properties",
            "baseName": "properties",
            "type": "any",
            "format": ""
        },
        {
            "name": "additionalProperties",
            "baseName": "additionalProperties",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "required",
            "baseName": "required",
            "type": "Array<string>",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return JsonSchema.attributeTypeMap;
    }

    public constructor() {
    }
}
