/**
 * DocSpring API
 * Use DocSpring\'s API to programmatically fill out PDF forms, convert HTML to PDFs, merge PDFs, or request legally binding e-signatures.
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { SubmissionPreview } from '../models/SubmissionPreview';
import { HttpFile } from '../http/http';

export class SubmissionBatchWithSubmissions {
    'id': string | null;
    'state': SubmissionBatchWithSubmissionsStateEnum;
    'metadata': any;
    'processed_at': string | null;
    'total_count': number;
    'pending_count': number;
    'error_count': number;
    'completion_percentage': number;
    'submissions'?: Array<SubmissionPreview>;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "id",
            "baseName": "id",
            "type": "string",
            "format": ""
        },
        {
            "name": "state",
            "baseName": "state",
            "type": "SubmissionBatchWithSubmissionsStateEnum",
            "format": ""
        },
        {
            "name": "metadata",
            "baseName": "metadata",
            "type": "any",
            "format": ""
        },
        {
            "name": "processed_at",
            "baseName": "processed_at",
            "type": "string",
            "format": ""
        },
        {
            "name": "total_count",
            "baseName": "total_count",
            "type": "number",
            "format": ""
        },
        {
            "name": "pending_count",
            "baseName": "pending_count",
            "type": "number",
            "format": ""
        },
        {
            "name": "error_count",
            "baseName": "error_count",
            "type": "number",
            "format": ""
        },
        {
            "name": "completion_percentage",
            "baseName": "completion_percentage",
            "type": "number",
            "format": ""
        },
        {
            "name": "submissions",
            "baseName": "submissions",
            "type": "Array<SubmissionPreview>",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return SubmissionBatchWithSubmissions.attributeTypeMap;
    }

    public constructor() {
    }
}

export enum SubmissionBatchWithSubmissionsStateEnum {
    Pending = 'pending',
    Processed = 'processed',
    Error = 'error'
}

