/**
 * DocSpring API
 * DocSpring provides an API that helps you fill out and sign PDF templates.
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

export class SubmissionDataRequestEvent {
    'id': string | null;
    'submissionId': string | null;
    'submissionDataRequestId': string | null;
    'eventType': SubmissionDataRequestEventEventTypeEnum;
    'messageType': SubmissionDataRequestEventMessageTypeEnum | null;
    'messageRecipient': string | null;
    'occurredAt': string | null;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "id",
            "baseName": "id",
            "type": "string",
            "format": ""
        },
        {
            "name": "submissionId",
            "baseName": "submission_id",
            "type": "string",
            "format": ""
        },
        {
            "name": "submissionDataRequestId",
            "baseName": "submission_data_request_id",
            "type": "string",
            "format": ""
        },
        {
            "name": "eventType",
            "baseName": "event_type",
            "type": "SubmissionDataRequestEventEventTypeEnum",
            "format": ""
        },
        {
            "name": "messageType",
            "baseName": "message_type",
            "type": "SubmissionDataRequestEventMessageTypeEnum",
            "format": ""
        },
        {
            "name": "messageRecipient",
            "baseName": "message_recipient",
            "type": "string",
            "format": ""
        },
        {
            "name": "occurredAt",
            "baseName": "occurred_at",
            "type": "string",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return SubmissionDataRequestEvent.attributeTypeMap;
    }

    public constructor() {
    }
}

export enum SubmissionDataRequestEventEventTypeEnum {
    SendRequest = 'send_request',
    ViewRequest = 'view_request',
    AcceptedTerms = 'accepted_terms',
    DeclineRequest = 'decline_request',
    SignRequest = 'sign_request',
    AllCompleted = 'all_completed'
}
export enum SubmissionDataRequestEventMessageTypeEnum {
    Email = 'email',
    Sms = 'sms',
    Fax = 'fax',
    Mail = 'mail',
    Slack = 'slack',
    Msteams = 'msteams',
    Discord = 'discord',
    Telegram = 'telegram',
    Whatsapp = 'whatsapp'
}

