/**
 * DocSpring API
 * Use DocSpring\'s API to programmatically fill out PDF forms, convert HTML to PDFs, merge PDFs, or request legally binding e-signatures.
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { SubmissionPreview } from '../models/SubmissionPreview';
import { HttpFile } from '../http/http';

export class Submission422Response {
    'status': Submission422ResponseStatusEnum;
    /**
    * Single error message (for non-validation errors)
    */
    'error'?: string;
    'submission'?: SubmissionPreview;
    /**
    * Array of validation error messages (when submission data is invalid)
    */
    'errors'?: Array<string>;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "status",
            "baseName": "status",
            "type": "Submission422ResponseStatusEnum",
            "format": ""
        },
        {
            "name": "error",
            "baseName": "error",
            "type": "string",
            "format": ""
        },
        {
            "name": "submission",
            "baseName": "submission",
            "type": "SubmissionPreview",
            "format": ""
        },
        {
            "name": "errors",
            "baseName": "errors",
            "type": "Array<string>",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return Submission422Response.attributeTypeMap;
    }

    public constructor() {
    }
}

export enum Submission422ResponseStatusEnum {
    Error = 'error'
}

