/**
 * DocSpring API
 * Use DocSpring\'s API to programmatically fill out PDF forms, convert HTML to PDFs, merge PDFs, or request legally binding e-signatures.
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

export class SubmissionDataRequestShow {
    'id': string | null;
    'email': string | null;
    'name': string | null;
    'order': number | null;
    'sort_order': number;
    'fields': Array<string> | null;
    'metadata': any | null;
    'state': SubmissionDataRequestShowStateEnum;
    'viewed_at': string | null;
    'completed_at': string | null;
    'data': any | null;
    'auth_type': SubmissionDataRequestShowAuthTypeEnum;
    'auth_second_factor_type': SubmissionDataRequestShowAuthSecondFactorTypeEnum;
    'auth_provider': string | null;
    'auth_session_started_at': string | null;
    'auth_session_id_hash': string | null;
    'auth_user_id_hash': string | null;
    'auth_username_hash': string | null;
    'auth_phone_number_hash': string | null;
    'ip_address': string | null;
    'user_agent': string | null;
    'submission_id': string | null;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "id",
            "baseName": "id",
            "type": "string",
            "format": ""
        },
        {
            "name": "email",
            "baseName": "email",
            "type": "string",
            "format": ""
        },
        {
            "name": "name",
            "baseName": "name",
            "type": "string",
            "format": ""
        },
        {
            "name": "order",
            "baseName": "order",
            "type": "number",
            "format": ""
        },
        {
            "name": "sort_order",
            "baseName": "sort_order",
            "type": "number",
            "format": ""
        },
        {
            "name": "fields",
            "baseName": "fields",
            "type": "Array<string>",
            "format": ""
        },
        {
            "name": "metadata",
            "baseName": "metadata",
            "type": "any",
            "format": ""
        },
        {
            "name": "state",
            "baseName": "state",
            "type": "SubmissionDataRequestShowStateEnum",
            "format": ""
        },
        {
            "name": "viewed_at",
            "baseName": "viewed_at",
            "type": "string",
            "format": ""
        },
        {
            "name": "completed_at",
            "baseName": "completed_at",
            "type": "string",
            "format": ""
        },
        {
            "name": "data",
            "baseName": "data",
            "type": "any",
            "format": ""
        },
        {
            "name": "auth_type",
            "baseName": "auth_type",
            "type": "SubmissionDataRequestShowAuthTypeEnum",
            "format": ""
        },
        {
            "name": "auth_second_factor_type",
            "baseName": "auth_second_factor_type",
            "type": "SubmissionDataRequestShowAuthSecondFactorTypeEnum",
            "format": ""
        },
        {
            "name": "auth_provider",
            "baseName": "auth_provider",
            "type": "string",
            "format": ""
        },
        {
            "name": "auth_session_started_at",
            "baseName": "auth_session_started_at",
            "type": "string",
            "format": ""
        },
        {
            "name": "auth_session_id_hash",
            "baseName": "auth_session_id_hash",
            "type": "string",
            "format": ""
        },
        {
            "name": "auth_user_id_hash",
            "baseName": "auth_user_id_hash",
            "type": "string",
            "format": ""
        },
        {
            "name": "auth_username_hash",
            "baseName": "auth_username_hash",
            "type": "string",
            "format": ""
        },
        {
            "name": "auth_phone_number_hash",
            "baseName": "auth_phone_number_hash",
            "type": "string",
            "format": ""
        },
        {
            "name": "ip_address",
            "baseName": "ip_address",
            "type": "string",
            "format": ""
        },
        {
            "name": "user_agent",
            "baseName": "user_agent",
            "type": "string",
            "format": ""
        },
        {
            "name": "submission_id",
            "baseName": "submission_id",
            "type": "string",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return SubmissionDataRequestShow.attributeTypeMap;
    }

    public constructor() {
    }
}

export enum SubmissionDataRequestShowStateEnum {
    Pending = 'pending',
    Completed = 'completed'
}
export enum SubmissionDataRequestShowAuthTypeEnum {
    None = 'none',
    Password = 'password',
    Oauth = 'oauth',
    EmailLink = 'email_link',
    PhoneNumber = 'phone_number',
    Ldap = 'ldap',
    Saml = 'saml'
}
export enum SubmissionDataRequestShowAuthSecondFactorTypeEnum {
    None = 'none',
    PhoneNumber = 'phone_number',
    Totp = 'totp',
    MobilePush = 'mobile_push',
    SecurityKey = 'security_key',
    Fingerprint = 'fingerprint'
}

