/**
 * DocSpring API
 * DocSpring provides an API that helps you fill out and sign PDF templates.
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { SubmissionAction } from '../models/SubmissionAction';
import { SubmissionDataRequest } from '../models/SubmissionDataRequest';
import { HttpFile } from '../http/http';

export class Submission {
    'batchId': string | null;
    'dataRequests': Array<SubmissionDataRequest>;
    'editable': boolean | null;
    'expired': boolean;
    'expiresAt': string | null;
    'id': string | null;
    'jsonSchemaErrors': Array<string> | null;
    'metadata': any;
    'password': string | null;
    'processedAt': string | null;
    'state': SubmissionStateEnum;
    'templateId': string | null;
    'templateType': SubmissionTemplateTypeEnum;
    'templateVersion': string | null;
    'test': boolean;
    'truncatedText': any | null;
    'pdfHash': string | null;
    'downloadUrl': string | null;
    'permanentDownloadUrl': string | null;
    'previewDownloadUrl': string | null;
    'previewGeneratedAt': string | null;
    'auditTrailDownloadUrl': string | null;
    'actions': Array<SubmissionAction>;
    'source': SubmissionSourceEnum;
    'referrer': string | null;
    'data': any | null;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "batchId",
            "baseName": "batch_id",
            "type": "string",
            "format": ""
        },
        {
            "name": "dataRequests",
            "baseName": "data_requests",
            "type": "Array<SubmissionDataRequest>",
            "format": ""
        },
        {
            "name": "editable",
            "baseName": "editable",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "expired",
            "baseName": "expired",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "expiresAt",
            "baseName": "expires_at",
            "type": "string",
            "format": ""
        },
        {
            "name": "id",
            "baseName": "id",
            "type": "string",
            "format": ""
        },
        {
            "name": "jsonSchemaErrors",
            "baseName": "json_schema_errors",
            "type": "Array<string>",
            "format": ""
        },
        {
            "name": "metadata",
            "baseName": "metadata",
            "type": "any",
            "format": ""
        },
        {
            "name": "password",
            "baseName": "password",
            "type": "string",
            "format": ""
        },
        {
            "name": "processedAt",
            "baseName": "processed_at",
            "type": "string",
            "format": ""
        },
        {
            "name": "state",
            "baseName": "state",
            "type": "SubmissionStateEnum",
            "format": ""
        },
        {
            "name": "templateId",
            "baseName": "template_id",
            "type": "string",
            "format": ""
        },
        {
            "name": "templateType",
            "baseName": "template_type",
            "type": "SubmissionTemplateTypeEnum",
            "format": ""
        },
        {
            "name": "templateVersion",
            "baseName": "template_version",
            "type": "string",
            "format": ""
        },
        {
            "name": "test",
            "baseName": "test",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "truncatedText",
            "baseName": "truncated_text",
            "type": "any",
            "format": ""
        },
        {
            "name": "pdfHash",
            "baseName": "pdf_hash",
            "type": "string",
            "format": ""
        },
        {
            "name": "downloadUrl",
            "baseName": "download_url",
            "type": "string",
            "format": ""
        },
        {
            "name": "permanentDownloadUrl",
            "baseName": "permanent_download_url",
            "type": "string",
            "format": ""
        },
        {
            "name": "previewDownloadUrl",
            "baseName": "preview_download_url",
            "type": "string",
            "format": ""
        },
        {
            "name": "previewGeneratedAt",
            "baseName": "preview_generated_at",
            "type": "string",
            "format": ""
        },
        {
            "name": "auditTrailDownloadUrl",
            "baseName": "audit_trail_download_url",
            "type": "string",
            "format": ""
        },
        {
            "name": "actions",
            "baseName": "actions",
            "type": "Array<SubmissionAction>",
            "format": ""
        },
        {
            "name": "source",
            "baseName": "source",
            "type": "SubmissionSourceEnum",
            "format": ""
        },
        {
            "name": "referrer",
            "baseName": "referrer",
            "type": "string",
            "format": ""
        },
        {
            "name": "data",
            "baseName": "data",
            "type": "any",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return Submission.attributeTypeMap;
    }

    public constructor() {
    }
}

export enum SubmissionStateEnum {
    Pending = 'pending',
    Processed = 'processed',
    InvalidData = 'invalid_data',
    Error = 'error',
    ImageDownloadFailed = 'image_download_failed',
    ImageProcessingFailed = 'image_processing_failed',
    WaitingForDataRequests = 'waiting_for_data_requests',
    SyntaxError = 'syntax_error',
    AccountSuspended = 'account_suspended',
    LicenseRevoked = 'license_revoked',
    Accidental = 'accidental'
}
export enum SubmissionTemplateTypeEnum {
    Pdf = 'pdf',
    Html = 'html'
}
export enum SubmissionSourceEnum {
    Api = 'api',
    Web = 'web',
    Reprocess = 'reprocess',
    Webhook = 'webhook'
}

