/**
 * DocSpring API
 * Use DocSpring\'s API to programmatically fill out PDF forms, convert HTML to PDFs, merge PDFs, or request legally binding e-signatures.
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

export class Template {
    'add_data_request_submission_id_footers': boolean;
    'allow_additional_properties': boolean;
    'description': string | null;
    'document_filename': string | null;
    'document_md5': string | null;
    'document_parse_error': boolean;
    'document_processed': boolean;
    'document_state': TemplateDocumentStateEnum;
    'document_url': string | null;
    'editable_submissions': boolean;
    'embed_domains': string | null;
    'encrypt_pdfs_password': string | null;
    'encrypt_pdfs': boolean;
    'expiration_interval': string;
    'expire_after': number;
    'expire_submissions': boolean;
    'external_predefined_fields_template_id': string | null;
    'external_predefined_fields_template_name': string | null;
    'first_template': boolean;
    'id': string | null;
    'locked': boolean;
    'merge_audit_trail_pdf': boolean;
    'name': string | null;
    'page_count': number;
    'page_dimensions': Array<Array<number>> | null;
    'parent_folder_id': string | null;
    'path': string | null;
    'permanent_document_url': string | null;
    'public_submissions': boolean;
    'public_web_form': boolean;
    'redirect_url': string | null;
    'slack_webhook_url': string | null;
    'template_type': TemplateTemplateTypeEnum;
    'updated_at': string | null;
    'version_published_at': string | null;
    'version': string | null;
    'webhook_url': string | null;
    'demo': boolean;
    'latest_version': string | null;
    'last_changed_at': string | null;
    'last_changed_by_type': TemplateLastChangedByTypeEnum | null;
    'last_changed_by_id': string | null;
    'defaults': any;
    'field_order': Array<Array<number>>;
    'fields': any;
    'footer_html': string | null;
    'header_html': string | null;
    'html_engine_options': any;
    'html': string | null;
    'predefined_fields': Array<any>;
    'scss': string | null;
    'shared_field_data': any;
    'versions': Array<any>;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "add_data_request_submission_id_footers",
            "baseName": "add_data_request_submission_id_footers",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "allow_additional_properties",
            "baseName": "allow_additional_properties",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "description",
            "baseName": "description",
            "type": "string",
            "format": ""
        },
        {
            "name": "document_filename",
            "baseName": "document_filename",
            "type": "string",
            "format": ""
        },
        {
            "name": "document_md5",
            "baseName": "document_md5",
            "type": "string",
            "format": ""
        },
        {
            "name": "document_parse_error",
            "baseName": "document_parse_error",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "document_processed",
            "baseName": "document_processed",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "document_state",
            "baseName": "document_state",
            "type": "TemplateDocumentStateEnum",
            "format": ""
        },
        {
            "name": "document_url",
            "baseName": "document_url",
            "type": "string",
            "format": ""
        },
        {
            "name": "editable_submissions",
            "baseName": "editable_submissions",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "embed_domains",
            "baseName": "embed_domains",
            "type": "string",
            "format": ""
        },
        {
            "name": "encrypt_pdfs_password",
            "baseName": "encrypt_pdfs_password",
            "type": "string",
            "format": ""
        },
        {
            "name": "encrypt_pdfs",
            "baseName": "encrypt_pdfs",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "expiration_interval",
            "baseName": "expiration_interval",
            "type": "string",
            "format": ""
        },
        {
            "name": "expire_after",
            "baseName": "expire_after",
            "type": "number",
            "format": ""
        },
        {
            "name": "expire_submissions",
            "baseName": "expire_submissions",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "external_predefined_fields_template_id",
            "baseName": "external_predefined_fields_template_id",
            "type": "string",
            "format": ""
        },
        {
            "name": "external_predefined_fields_template_name",
            "baseName": "external_predefined_fields_template_name",
            "type": "string",
            "format": ""
        },
        {
            "name": "first_template",
            "baseName": "first_template",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "id",
            "baseName": "id",
            "type": "string",
            "format": ""
        },
        {
            "name": "locked",
            "baseName": "locked",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "merge_audit_trail_pdf",
            "baseName": "merge_audit_trail_pdf",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "name",
            "baseName": "name",
            "type": "string",
            "format": ""
        },
        {
            "name": "page_count",
            "baseName": "page_count",
            "type": "number",
            "format": ""
        },
        {
            "name": "page_dimensions",
            "baseName": "page_dimensions",
            "type": "Array<Array<number>>",
            "format": ""
        },
        {
            "name": "parent_folder_id",
            "baseName": "parent_folder_id",
            "type": "string",
            "format": ""
        },
        {
            "name": "path",
            "baseName": "path",
            "type": "string",
            "format": ""
        },
        {
            "name": "permanent_document_url",
            "baseName": "permanent_document_url",
            "type": "string",
            "format": ""
        },
        {
            "name": "public_submissions",
            "baseName": "public_submissions",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "public_web_form",
            "baseName": "public_web_form",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "redirect_url",
            "baseName": "redirect_url",
            "type": "string",
            "format": ""
        },
        {
            "name": "slack_webhook_url",
            "baseName": "slack_webhook_url",
            "type": "string",
            "format": ""
        },
        {
            "name": "template_type",
            "baseName": "template_type",
            "type": "TemplateTemplateTypeEnum",
            "format": ""
        },
        {
            "name": "updated_at",
            "baseName": "updated_at",
            "type": "string",
            "format": ""
        },
        {
            "name": "version_published_at",
            "baseName": "version_published_at",
            "type": "string",
            "format": ""
        },
        {
            "name": "version",
            "baseName": "version",
            "type": "string",
            "format": ""
        },
        {
            "name": "webhook_url",
            "baseName": "webhook_url",
            "type": "string",
            "format": ""
        },
        {
            "name": "demo",
            "baseName": "demo",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "latest_version",
            "baseName": "latest_version",
            "type": "string",
            "format": ""
        },
        {
            "name": "last_changed_at",
            "baseName": "last_changed_at",
            "type": "string",
            "format": ""
        },
        {
            "name": "last_changed_by_type",
            "baseName": "last_changed_by_type",
            "type": "TemplateLastChangedByTypeEnum",
            "format": ""
        },
        {
            "name": "last_changed_by_id",
            "baseName": "last_changed_by_id",
            "type": "string",
            "format": ""
        },
        {
            "name": "defaults",
            "baseName": "defaults",
            "type": "any",
            "format": ""
        },
        {
            "name": "field_order",
            "baseName": "field_order",
            "type": "Array<Array<number>>",
            "format": ""
        },
        {
            "name": "fields",
            "baseName": "fields",
            "type": "any",
            "format": ""
        },
        {
            "name": "footer_html",
            "baseName": "footer_html",
            "type": "string",
            "format": ""
        },
        {
            "name": "header_html",
            "baseName": "header_html",
            "type": "string",
            "format": ""
        },
        {
            "name": "html_engine_options",
            "baseName": "html_engine_options",
            "type": "any",
            "format": ""
        },
        {
            "name": "html",
            "baseName": "html",
            "type": "string",
            "format": ""
        },
        {
            "name": "predefined_fields",
            "baseName": "predefined_fields",
            "type": "Array<any>",
            "format": ""
        },
        {
            "name": "scss",
            "baseName": "scss",
            "type": "string",
            "format": ""
        },
        {
            "name": "shared_field_data",
            "baseName": "shared_field_data",
            "type": "any",
            "format": ""
        },
        {
            "name": "versions",
            "baseName": "versions",
            "type": "Array<any>",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return Template.attributeTypeMap;
    }

    public constructor() {
    }
}

export enum TemplateDocumentStateEnum {
    Pending = 'pending',
    Processed = 'processed',
    PasswordRequired = 'password_required',
    MalformedPdf = 'malformed_pdf',
    UnknownError = 'unknown_error'
}
export enum TemplateTemplateTypeEnum {
    Pdf = 'pdf',
    Html = 'html'
}
export enum TemplateLastChangedByTypeEnum {
    User = 'user',
    Api = 'api'
}

