/**
 * DocSpring API
 * DocSpring provides an API that helps you fill out and sign PDF templates.
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

export class UploadPresignResponse {
    'fields': any;
    'headers': any;
    'url': string;
    'method'?: UploadPresignResponseMethodEnum;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "fields",
            "baseName": "fields",
            "type": "any",
            "format": ""
        },
        {
            "name": "headers",
            "baseName": "headers",
            "type": "any",
            "format": ""
        },
        {
            "name": "url",
            "baseName": "url",
            "type": "string",
            "format": ""
        },
        {
            "name": "method",
            "baseName": "method",
            "type": "UploadPresignResponseMethodEnum",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return UploadPresignResponse.attributeTypeMap;
    }

    public constructor() {
    }
}

export enum UploadPresignResponseMethodEnum {
    Post = 'post'
}

